repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      # - id: bundler-check
      # - id: check-mailmap
      # - id: fasterer
      # - id: forbid-binary
      # - id: forbid-space-in-indent
      # - id: git-check
      # - id: git-dirty
      # - id: markdownlint
      # - id: reek
      # - id: require-ascii
      # - id: rubocop
      # - id: script-must-have-extension
      # - id: script-must-not-have-extension
      - id: shellcheck
      # - id: shfmt

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args:
          - "--unsafe"
          - "--allow-multiple-documents"
      - id: end-of-file-fixer
      # -id: no-commit-to-branch
        # args:
          # - "-b, master"
          # - "-b, release"
          # - "-b, develop"
      - id: pretty-format-json
        args:
          - "--autofix"
          # - "--indent 4"
      - id: trailing-whitespace
      - id: check-merge-conflict
