# https://numtide.github.io/devshell
[[commands]]
package = "just"

[[commands]]
package = "terraform"

[devshell]
packages = [
    "terraform-providers.minio",
    "terraform-providers.vault",
    "terraform-providers.cloudflare",
]
