iscsi_packages:
  - open-iscsi

iscsi_initiator_name: "iqn.2024-04.com.pwnyboy:{{ ansible_facts['nodename'] }}"

iscsi_targets: []

# open-iscsi configuration
iscsi_auto_start: false
iscsi_leading_login: false

# Authentication
iscsi_authentication: false
iscsi_auth_username: ''
iscsi_auth_password: ''
iscsi_auth_username_in: ''
iscsi_auth_password_in: ''

# Timeouts
iscsi_replacement_timeout: 120
iscsi_login_timeout: 15
iscsi_noop_out_interval: 5
iscsi_noop_out_timeout: 5
iscsi_abort_timeout: 15
iscsi_lu_reset_timeout: 30
iscsi_tgt_reset_timeout: 30

# Retry
iscsi_initial_login_retry_max: 8

# Session and device queue depth
iscsi_cmds_max: 128
iscsi_queue_depth: 32

# Misc system performance settings
iscsi_thread_priority: -20

# ISCSI Settings
iscsi_initialr2t: false
iscsi_immediate_data: true
iscsi_first_burst_length: 262144
iscsi_max_burst_length: 16776192
iscsi_max_rev_length: 262144
iscsi_max_xmit_length: 0
iscsi_discovery_max_recv_length: 32768
iscsi_nr_sessions: 1
iscsi_fast_abort: true
iscsi_auto_scan: true
